name: Delete Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm the deletion of the infrastructure'
        required: true

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: e-commerce-cluster

jobs:
  delete-infrastructure:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_delete == 'DELETE'
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Update kube config
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Delete Kubernetes resources
      run: |
        kubectl delete deployment,service,ingress --all --all-namespaces

    - name: Delete EKS cluster
      run: |
        aws eks delete-cluster --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Delete CloudFormation stack
      run: |
        aws cloudformation delete-stack --stack-name ${{ env.CLUSTER_NAME }}

    - name: Wait for stack deletion
      run: |
        aws cloudformation wait stack-delete-complete --stack-name ${{ env.CLUSTER_NAME }}

    - name: Confirm deletion
      run: |
        echo "Infrastructure deletion complete."